services:
  gemini-cli:
    image: naoyoshinori/gemini-cli:0-node
    working_dir: /workspace/dotfiles
    volumes:
      - ~/.gitconfig:/home/node/.gitconfig
      - ~/.gemini:/home/node/.gemini:cached
      - .:/workspace/dotfiles:cached
    env_file:
      - ~/.env.gemini
    command: ["sleep", "infinity"]
